
 
services:
 
  auth-service:
    build:
      context: .
      dockerfile: apps/auth-service/Dockerfile
    container_name: auth-service
    expose:
      - "4001"
    env_file:
      - apps/auth-service/.env
    environment:
      DB_HOST: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
 
  web-app:
    build:
      context: .
      dockerfile: apps/web-app/Dockerfile
    container_name: clinic-frontend
    volumes:
      - web_dist:/app/dist
 
  nginx:
    image: nginx:latest
    container_name: clinic-nginx
    ports:
      - "8080:80"
    volumes:
      - web_dist:/usr/share/nginx/html
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth-service
      - web-app
 
  postgres:
    image: postgres:15
    container_name: clinic-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clinic_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
 
  redis:
    image: redis:latest
    container_name: clinic-redis
 
volumes:
  postgres_data:
  web_dist: