services:
  api-server:
    build:
      context: .
    container_name: api-server
    ports:
      - '5000:5000'
    volumes:
      - ./apps/api-server:/apps
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres


  postgres:
    image: postgres:15
    container_name: clinic-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clinic_db
    volumes:
      - postgres_data:/var/lib/postgressql/data


  nginx:
    image: nginx:latest
    container_name: clinic-nginx
    ports:
      - '80:80'
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-server

volumes:
  postgres_data:
