services:
  auth-service:
    build:
      context: .
      dockerfile: apps/auth-service/Dockerfile
    container_name: auth-service
    expose:
      - '4001'
    env_file:
      - apps/auth-service/.env
    environment:
      DB_HOST: postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: clinic-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clinic_db
    volumes:
      - postgres_data:/var/lib/postgresql/data


  nginx:
    image: nginx:latest
    container_name: clinic-nginx
    ports:
      - '8080:80'
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth-service

volumes:
  postgres_data:
