openapi: 3.0.0

info:
  title: Patient Service API
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Gateway

paths:

  /api/patient/profile:
    post:
      summary: Create profile
      tags: [Patient]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                  example: Delhi
                emergencyContact:
                  type: string
                  example: 6789098765
      responses:
        "201":
          description: Patient Profile created successfully
        "409":
          description: Profile already exists
        "400":
          description: Validation error

  /api/patient/me:
    get:
      summary: Get profile
      tags: [Patient]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Profile

  /api/patient?:
    get:
      summary: List patients
      tags: [Patient]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Patients list

  # /api/patient/me:
  #   delete:
  #     summary: Delete Profile
  #     tags:
  #       - Patient
  #     security:
  #       - bearerAuth: []
  #     responses:
  #       200:
  #         description: Profile deleted successfully

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT




